### ISSUE TITLE
`TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'`

### ISSUE THREAD

**Issue by saforem2** [microsoft/Megatron-DeepSpeed#215]
I believe the relevant line is:
https://github.com/microsoft/Megatron-DeepSpeed/blob/c2b073624eadabfd898780a6306000db9dee1836/megatron/training.py#L701

Trying to run: 

```bash
MASTER_ADDR="localhost" MASTER_PORT=5432 RANK=0 WORLD_SIZE=8 python3 pretrain_gpt.py \
    --seed 14103 --DDP-impl local --pipeline-model-parallel-size 1 --tensor-model-parallel-size 1 \
    --num-layers 48 --hidden-size 1536 --num-attention-heads 24 --micro-batch-size 1 --global-batch-size 8 \
    --seq-length 2048 --max-position-embeddings 2048 --train-iters 5 --lr-decay-iters 320000 --num-workers 1 \
    --data-path ../dataset/BookCorpusDataset_text_document \
    --vocab-file ../dataset/gpt2-vocab.json \
    --merge-file ../dataset/gpt2-merges.txt \
    --data-impl mmap --split 949,50,1 --distributed-backend nccl --lr 0.00015 --lr-decay-style cosine \
    --min-lr 1.0e-5 --weight-decay 1e-2 --clip-grad 1.0 --lr-warmup-fraction .01 --log-interval 1 \
    --save-interval 1000 --eval-interval 1000 --eval-iters 1 --override-opt_param-scheduler \
    --checkpoint-activations --checkpoint-num-layers 1 \
    --fp16 --deepspeed-activation-checkpointing \
    --no-pipeline-parallel \
    --zero-stage=0 
    --deepspeed_config=../ds_config-gpt.json \
    --deepspeed_mpi \
    --deepspeed
```

I get the following Traceback:

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/projects/microsoft/Megatron-DeepSpee │
│ d/pretrain_gpt.py:338 in <module>                                                                │
│                                                                                                  │
│   335                                                                                            │
│   336 if __name__ == "__main__":                                                                 │
│   337 │   git_ds_info()                                                                          │
│ ❱ 338 │   pretrain(train_valid_test_datasets_provider,                                           │
│   339 │   │   │    model_provider,                                                               │
│   340 │   │   │    ModelType.encoder_or_decoder,                                                 │
│   341 │   │   │    forward_step,                                                                 │
│                                                                                                  │
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/projects/microsoft/Megatron-DeepSpee │
│ d/megatron/training.py:198 in pretrain                                                           │
│                                                                                                  │
│    195 │   │                                                                                     │
│    196 │   │   iteration = 0                                                                     │
│    197 │   │   if args.do_train and args.train_iters > 0:                                        │
│ ❱  198 │   │   │   iteration = train(forward_step_func,                                          │
│    199 │   │   │   │   │   │   │   model, optimizer, opt_param_scheduler,                        │
│    200 │   │   │   │   │   │   │   train_data_iterator, valid_data_iterator,                     │
│    201 │   │   │   │   │   │   │   process_non_loss_data_func)                                   │
│                                                                                                  │
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/projects/microsoft/Megatron-DeepSpee │
│ d/megatron/training.py:1123 in train                                                             │
│                                                                                                  │
│   1120 │   │   │   │   │   args.iteration + 1)                                                   │
│   1121 │   │   args.curr_iteration = iteration                                                   │
│   1122 │   │   loss_dict, skipped_iter, grad_norm, num_zeros_in_grad = \                         │
│ ❱ 1123 │   │   │   train_step(forward_step_func,                                                 │
│   1124 │   │   │   │   │      train_data_iterator,                                               │
│   1125 │   │   │   │   │      model,                                                             │
│   1126 │   │   │   │   │      optimizer,                                                         │
│                                                                                                  │
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/projects/microsoft/Megatron-DeepSpee │
│ d/megatron/training.py:701 in train_step                                                         │
│                                                                                                  │
│    698 │   │   increment = get_num_microbatches() * \                                            │
│    699 │   │   │   │   │   args.micro_batch_size * \                                             │
│    700 │   │   │   │   │   args.data_parallel_size                                               │
│ ❱  701 │   │   model[0].step(lr_kwargs={'increment': increment})                                 │
│    702 │   │   update_successful = model[0].was_step_applied()                                   │
│    703 │   else:                                                                                 │
│    704 │   │   update_successful, grad_norm, num_zeros_in_grad = optimizer.step(args, timers)    │
│                                                                                                  │
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/miniconda3/envs/2023-04-26/lib/pytho │
│ n3.10/site-packages/deepspeed/runtime/engine.py:2083 in step                                     │
│                                                                                                  │
│   2080 │   │   │   │   │   and self.quantizer.any_precision_switch()):                           │
│   2081 │   │   │   │   self._take_model_step(lr_kwargs, self.block_eigenvalue)                   │
│   2082 │   │   │   else:                                                                         │
│ ❱ 2083 │   │   │   │   self._take_model_step(lr_kwargs)                                          │
│   2084 │   │   │                                                                                 │
│   2085 │   │   │   report_progress = self.global_rank == 0 if self.global_rank else True         │
│   2086                                                                                           │
│                                                                                                  │
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/miniconda3/envs/2023-04-26/lib/pytho │
│ n3.10/site-packages/deepspeed/runtime/engine.py:2037 in _take_model_step                         │
│                                                                                                  │
│   2034 │   │   │   │   │   # XXX Hack to work with Megatron 2.0 and DeepSpeed pipelines.         │
│   2035 │   │   │   │   │   # We don't currently have a way to specify lr_kwargs from             │
│   2036 │   │   │   │   │   # pipe_engine.train_batch()                                           │
│ ❱ 2037 │   │   │   │   │   self.lr_scheduler.step(increment=self.train_batch_size())             │
│   2038 │   │                                                                                     │
│   2039 │   │   if report_progress and (self.global_steps + 1) % self.steps_per_print() == 0:     │
│   2040 │   │   │   self._report_progress(self.global_steps + 1)                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'
```

I believe the issue is that this `model.step` _requires_ a `lr_kwargs` dict. The relevant lines start at

https://github.com/microsoft/DeepSpeed/blob/9d79cfd1e90cae9306dc1b5837d374b2c9489ac8/deepspeed/runtime/engine.py#L2031

```python
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /lus/grand/projects/datascience/foremans/locations/thetaGPU/miniconda3/envs/2023-04-26/lib/pytho │
│ n3.10/site-packages/deepspeed/runtime/engine.py:2032 in _take_model_step                         │
│                                                                                                  │
│   2029 │   │   │   self.compression_scheduler.step()                                             │
│   2030 │   │   │   if self.lr_scheduler is not None:                                             │
│   2031 │   │   │   │   try:                                                                      │
│ ❱ 2032 │   │   │   │   │   self.lr_scheduler.step(**(lr_kwargs or {}))                           │
│   2033 │   │   │   │   except TypeError:                                                         │
│   2034 │   │   │   │   │   # XXX Hack to work with Megatron 2.0 and DeepSpeed pipelines.         │
│   2035 │   │   │   │   │   # We don't currently have a way to specify lr_kwargs from             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'
```

so it will first try passing `self.lr_scheduler.step({'increment': increment})`, which will fail and then will try

```python
│   2034 │   │   │   │   │   # XXX Hack to work with Megatron 2.0 and DeepSpeed pipelines.         │
│   2035 │   │   │   │   │   # We don't currently have a way to specify lr_kwargs from             │
│   2036 │   │   │   │   │   # pipe_engine.train_batch()                                           │
│ ❱ 2037 │   │   │   │   │   self.lr_scheduler.step(increment=self.train_batch_size())
```

which again, fails with the same 

```python
TypeError: WarmupLR.step() got an unexpected keyword argument 'increment'
```

However, replacing 

```python
self.lr_scheduler.step(increment=self.train_batch_size())
```

with 

```python
self.lr_scheduler.step(self.train_batch_size())
```

(i.e. passing increment as an argument without the `increment=` keyword) seems to fix it.

I wasn't sure whether to raise this as an issue here or on https://github.com/microsoft/DeepSpeed, but I figured my chances are better here
